language: go
go:
- 1.13.x
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
dist: trusty
script:
- make lint
- make test
- sonar-scanner
after_script:
- make cover
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: $ORGANIZATION
    token: $SONAR_TOKEN
env:
  global:
  - GO111MODULE=on
