language: go
go:
- 1.12.x
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
before_install:
- chmod +x ./sonar.sh
script:
- make lint
- make test
- "./sonar.sh"
after_script:
- make cover
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud: true
env:
  global:
  - GO111MODULE=on
  - secure: jQHmaghOw+2JFpxaYkUodMxxn01LEfaG7KnrOPgapCWl7UOIQ/I80GzVhD1GupJTIBciUcgGlBCsQxMsFbVQ9ZHTZcJ9dAtSlvSXarrXBjg9lJv762KZVN8HhXCjduBkLzz0WTRCRfzW6h/40pKMA6saoRaspMIe9y76lF+pRGHlkzCjA6WuduuomRlKniMzKb8Xy3LhVEjHmcBHhjRaQRLEZmKMTBAQ+gdOVp332ToKvIBrUVNyXumU71FwL/mNtr0UQ2dYs9t/QmNP6TyiSF1HiequJ/RYBVheNxgumEEkInWLbL0iy4dV3ImM5qIU4UnyTFqHAVFnJhnr+AOJ7k4fclIeBWHJYPbowtUFRpqSeQUEbOZLkCtfcwyiZNnC0ymTuK7j6+LL1sPCODC+QBYljQ7x1JiVoKlnWNJ0sIPsKXrZOeMaHwZSyTvCk8j0gw1QinofVCTIZ4adjeCMY2dDEw4J2l7NkcA+K932+y73PTZD2j2MpbLBsGM4epp9Ohb1TI9O/TqV1DTCHl6Z4mfgRJKvHs0m16COnaqL2qR8QErRWa9RxyVpf20eEdrJBWcBIF/2fUnkRyl8vlWxZ0GVYlRwiKbXhTSdDS3Ne0+EY9aJPf8cyhTQtnNZxeVqbL8gW7hQQOKXtEplV3qtzghPWPvSHktoHqS58LK3M+E=
  - secure: cjuS6F23PgKf6hdjaOdUtvsE7EbGfCMUhe+vs9B6fnMEOrbUVLaqCNo7oNnStYCo2vh3MuPrSctRj+iQ6fOI++HC0RBBWtMUVHmXjFV9a+pOv+pioYOjQv5VgVSjB6kcceaaqxrMLmktECOH76tv5tU/mXU7dLz0Co6FMs32FHSWt82mviP2bqSIFPTdnyak/4KpI/fDud3nCk67kyLSz4k8bjIWaGHkUb5dQ/CHyzhkHwnDLshipkOSnhq7fwQUPLltdBVKMEntL+spU9fj05zYBdxOEhXOlJlcgD0GHsa3zZJvy9nZb0X7Ywe1Zn/Ptd5IzxkvIbjI67XpbLBYIjjty8DhDecHtNp9YNvYnd4+1nIHIjgXKvUpu6wHQbExYUjiHNj5D/X20Q6AEmQmlzTDVfuxEhC/jDFqYp9KZUG6c+CB4ZuWKMuoFGz1DG3b3vI5hr2sxN9e2mDCq2VbRP/ayQA05MhakOlnNfQ3IjHlt1ea9sZywo7fokVlAn88FNso926aN9TX12zEi4ixR58qD62li/7r7nkvvRSm6+lhd7W2yyCIlTpxBa/5YC7HPTQECirF3KG05LHJwHNwy3fYUX/EIfn/javc7Or625+i6uoBxHTUOQCwwKAjqyUD5RuEq8XzRHlMbSGOSrMnKeTKAwkNAv6vYW1b1WZAo64=
  - secure: EeIN0BgOxw7zDJAm9BtBLgnl+mSQJvyq2yIzdtlWEKd0za0SGGJW4j/A4P9gTkmp/wYyQGi7viaelf0OFFG8xKb2Lq0oCnPWAmZ3kVYCLLxHyNSGbqjxa6bcmVEQZ5i9VA3T30VqU7RSb4ytPxsoT7WWJHYjAu/8rZyjb6E0kPoc12kn0N8QEP7ie7TjumJEf+Q9zvM2Mr0xuj0dYx/Sxq7Qz8ivXgOwbw2urvjCcbkDn18kxPFSgKk2BuwOblufxSJq2rKbIJI1ktGJfUrqYWnCl1g3StnVAdNibU9KrBMm/vJmADyvHh9td9Ef3xjHA1hojNB2dO+Laq7UBi++WX7vf8s8FaYlmgCf84s1MLMftqYv6kJgoOO7sFW9o7oiWiG2wVvYy7oEunJfE2aBnztkdfig4xtS5ctWOLlIOroNWDSppQOsoaNEhJpb4LtXECydxaLYzoaJS7n57BoBU+9cOVtOzH8s+fWAeARZsZHtHtvGXu7GNjShZwN7PM4IegANE4CqNASC/tU28s6BbbIoqwwEr7d1zfax2lFUlvCz0sJCsqFO1jV+XyX0Eb8oSfuwurWB7EjxdKKH0lkj1ZSEg2UkwroMrDBdC5bkFH3Sd7kajrxL36FMnW6itdDBmEl1vYe9p2GmwFs29Q+BM5Yo9dZlZbjXbmHkha+tgto=
  - secure: fffaqPg+eGbvm7xCoNT0fzj+uWUVy8YxKOSMJ1gKXBglnsdAhz09+GhEmmu8pZu9ldsi0/+KYCTGGkZKCfdxu7Czi5RZ0AxKuBjWwsmVeoT3GfbfZKBJoGxvBZyG9QpNrgFLLMINvCydKZdN4fBFacnF4ewAt8RFlutNHIPsk6qfVSyjwCJhqBrDQfMGHKdZp8026JYL5eF7lqzaGvi7NjxIsxYiwK9/GTN87/ZLx/VJrle4KACFOkk/st3dVqpt/6WCkZMjbfanSZaBYlMQRJfK9VkniwjnoKIV2R6+Ke8Bxrt+UOuHjn8pSC4NX2a5Hy+MXpjVgZ7eXKZ1J7vwc6mjHSzrfVoSzv4+nJ0zFMeX+RQuyD/3gS8Ae9RogJBSiY12tYLiO1K5fiX8znVCI6oSELXucONcAnHNXf8gueM8QJBlC4JYTLrX43RR8T4KZBjnME/mc1QpfXBN+hu4OCP6qlfHvmM7ck356XmFo8Avfpj9pyf5HoSmkCFExeDE430KDc3HHbHBcG9pfSimse/wo2oaSXhwfBTHhcn7wZW7EoTvMssvgdC/3hE4NEqIer8J7YbB5QkhEm+UWGU6kNdSi2rj0Z1gksvmFPu91bB8D5ST96ZR4msVaXcipGdFipWb6SFOYae61eYScUTy5xTm5u0cuSgeL4bVTf96ZPg=
